.github/workflows/deploy.yml
README.md

Added documentation to the accessibility workflow.

Documentation.

---

.github/workflows/deploy.yml
README.md

This will fix it! The flags were causing errors because a pytest plugin was missing.

Accessibility testing

---

.github/workflows/deploy.yml

:bug: Fixed build bug.

---

.github/workflows/deploy.yml

- enable a db_upgrade option to allow db migrations
- added option for frontend assets to build assests rather than commented out lines

Incorporate db upgrade

---

.github/workflows/deploy.yml

Deploy to test wasn't running if deploy to dev was false. Fixed and simplified the condition

Fix test deploy conditions

---

.github/workflows/tag-to-release.yml

We only want to build assets on frontend apps where that step is applicable.
Adds an input parameter to make that step optional

FS-2172: make build static assets optional

---

.github/workflows/tag-to-release.yml

Adding if statement to the tagging job so that it won't run if a PR is closed but not merged.

adding if to tag job

---

.github/workflows/tag-to-release.yml
.github/workflows/test-tag-to-release.yml

Writes the new tag number out to the job summary to make it easier to find. It will appear on the run summary as per the screenshot below.

Bau show tag

---

.github/workflows/deploy.yml
.github/workflows/run-shared-tests.yml

https://digital.dclg.gov.uk/jira/browse/FS-1200
Added assessment store url to enable performance tests for Assessment store.
N/A
N/A

FS-1200: Enable performance tests for Assessment store to run in the pipelines

---

.github/workflows/deploy.yml

- Adds quotation marks surrounding the RSA keys
- These were previously set as part of the secret

BAU: Wrap RSA keys with quotation marks

---

.github/workflows/package.yml

* Some applications will not follow the format of 'funding-service-design-<app>' so minor modification needed to pass through the whole string
+semver: minor
+ref: FS-3193

Minor update to docker image

---

.github/workflows/package.yml

https://dluhcdigital.atlassian.net/browse/FS-3077
Use latest build pack rather than builder:base
(i.e. use builder-jammy-base)

FS-3077 Use latest build pack

---

.github/workflows/package.yml

* Adding in python source
* Setting up python venv
* Running build script
+ref: FS-3462
+semver: minor

Updating package workflow to include asset building

---

.github/workflows/package.yml

* Full includes many common libraries and utilities.
* Python requirements update adds in dependency on libpq-dev to be present on the client
+ref: FS-3622
+semver: minor

Updating paketo build image

---

.github/workflows/post-deploy.yml

Starter to include tests after deploy, as per https://dluhcdigital.atlassian.net/browse/FS-3337

FS-3337. Include post-deploy tests

---

.github/workflows/update-postaward-env.yml
.github/workflows/update-preaward-env.yml

* Differentiating the workflow descriptions
* Updating the environment names
+ref: FS-3549
+semver: minor

Update copilot workflows

---

.github/workflows/update-postaward-env.yml
.github/workflows/update-preaward-env.yml

* env deploy accepts name as a parameter, not env
+ref: FS-3549
+semver: minor

Updating env to name

---

.github/workflows/combine-prs.yml

* Adding a new workflow to combine PRs generated by dependabot to reduce stress on the support engineer
+ref: FS-2374
+semver: minor

Add a new workflow

---

apps/pre-award/copilot/environments/uat/manifest.yml

* Add the environment folder and the manifest file for UAT
+ref: FS-3719
+semver: minor

Add UAT manifest

---

.github/actions/copilot_setup/action.yml
.github/workflows/update-preaward-env.yml

* Adding a copilot setup action
* Updating pre-award env with DRY code
+ref: BAU
+semver: minor

Add action for copilot, split env updates

---

.github/workflows/update-preaward-env.yml

* Remove concurrency
* Remove dev reference that should be being built using matrix value
+ref: BAU
+semver: minor

Minor fixes

---

.github/workflows/run-shared-tests.yml

Reverts communitiesuk/funding-service-design-workflows#82

Revert "BAU: Upgrade Node Version to 19 for E2E Tests Workflow"

---

.github/workflows/pre-deploy.yml

* Pre deploy tests do not need a Personal Access Token to operate
+ref: BAU
+semver: minor

Remove PAT token

---

scripts/aws_cloudfoundry_bucket_pull.sh
scripts/aws_cloudfoundry_bucket_push.sh
scripts/aws_cloudfoundry_migrate.sh
scripts/aws_connect_db.sh

BAU - fix ENV not having a dollar sign in front

---

.github/workflows/combine-prs.yml

https://dluhcdigital.atlassian.net/browse/FS-3732

ammend pr workflow to use github app

---

.github/workflows/deploy.yml
.github/workflows/post-deploy.yml
.github/workflows/run-shared-tests.yml

* Added generate token job                                                                                                                                                                                                                   * Updated jobs to utilise generated token                                                                                                                                                                                                                                                                                                                                                                                                                                                 
+ref: FS-3826 …

FS-3826 - Adding in generated tokens instead of reliance on Personal Access Tokens      

---

scripts/aws_connect_db.sh

Add extra echo to give more information

BAU - Add extra info to help other DB GUIs

---

scripts/aws_cloudfoundry_bucket_pull.sh
scripts/aws_cloudfoundry_bucket_push.sh

Add some extra logging to aid with migration of files.

Bau extra logging

---

apps/pre-award/copilot/environments/addons/form-uploads.yml

* Updating permissions for uploading and downloading objects
* Add sub-keys for s3 bucket resources
* Exporting the _environment_ level output to allow access from the other services
+ref: BAU
+semver: minor

Updating permissions

---

.github/workflows/just-run-tests.yml

ADding new workflow to allow us to just run the tests againsta. specific aws env

added separate workflow to just run tests

---

apps/pre-award/copilot/environments/prod/manifest.yml

added cert to prod

---

apps/pre-award/copilot/environments/addons/funding-service-magic-links.yml
scripts/aws_connect_redis.sh

https://dluhcdigital.atlassian.net/browse/FS-3876
Allow a link using SSM through bastion to the Redis instances of each environment.

FS-3876 - Set up an SG connection to the Redis instance

---

readmes/python-repos-setup.md
readmes/python-repos-testing.md

Added static assests build steps

Added static assests build steps

---

scripts/aws_connect_db.sh

Add data-store to allow post-award data-store to connect to bastion host.

FMD-221: add data-store to service allowlist

---

.github/workflows/pre-deploy.yml

Updating checkout to use v4 and remove deprecation warnings

bumping checkout version to remove warnings in job output

---

.github/workflows/package.yml
.github/workflows/post-deploy.yml
.github/workflows/pre-deploy.yml
.github/workflows/run-shared-tests.yml
.github/workflows/tag-to-release.yml
.github/workflows/update-postaward-env.yml

https://dluhcdigital.atlassian.net/browse/FS-4058
Update the packages being uses to avoid deprecated actions.

FS-4058 Update actions packages

---

readmes/python-repos-ide-setup.md

https://dluhcdigital.atlassian.net/browse/FS-2713
Added flake8 setup instructions in readme

Added flake8 setup instructions readme

---

.github/workflows/post-deploy.yml

Reverting change of bandit version and path, because these cause failures. https://dluhcdigital.atlassian.net/browse/FS-4087 raised to fix properly

Bau bandit revert

---

.github/workflows/determine-jobs.yml

Adding new shared workflow to determine which jobs to run based on branch name

fs-4294 adding shared workflow to determine jobs

---

.github/workflows/determine-jobs.yml

Updating rules to only target dev env if deploying from a feature branch (removing test)

fs-4291 changing feature branches to just target dev

---

.github/workflows/package.yml
.github/workflows/pre-deploy.yml

Updated build and unit test to checkout the base repo.
Updated unit test tasks to install requirements from base repo

Fs 4462 build with base reqs

---

readmes/python-repos-ide-setup.md
readmes/python-repos-paketo.md
readmes/python-repos-setup.md

Updating info in the shared readmes to reference the dev containers and changed build setup

Updates to readmes for base image changes

---

apps/pre-award/copilot/environments/addons/post-award-cluster.yml
apps/pre-award/copilot/environments/addons/post-award-failed-files.yml
apps/pre-award/copilot/environments/addons/post-award-find-download-files.yml
apps/pre-award/copilot/environments/addons/post-award-find-downloads.yml
apps/pre-award/copilot/environments/addons/post-award-redis.yml
apps/pre-award/copilot/environments/addons/post-award-successful-files.yml
scripts/aws_db_dump_restore.sh

- Adds yml files for env level Postgres Database, S3 buckets and Redis for use by the new post-award combined services service which is deploying in the pre-award AWS App.

FPASF-263: Add post-award environment-level DB, Redis & S3 buckets to pre-award app

---

.github/workflows/package.yml
.github/workflows/pre-deploy.yml

revert base image changes to unblock post award team

Fix workflow

---

apps/pre-award/copilot/environments/prod/manifest.yml

Add new certificate ARNs to add new domain names

FPASF-249: update certificate ARNs for production

---

scripts/aws_connect_db.sh

Follow-up after: https://github.com/communitiesuk/funding-service-design-workflows/pull/163
Usage string needs to be updated to reflect changes.

BAU: Update usage message

---

apps/pre-award/copilot/environments/addons/notification-queue.yml
apps/pre-award/copilot/environments/addons/sanitised-database-dumps-access-policy.yml
apps/pre-award/copilot/environments/addons/sanitised-database-dumps.yml

This should create a sanitised data bucket (in the prod env only)
Note: currently this does not include policies for it to be accessed from other accounts, these should be added in subsequent PRs.

FPASF-223: Create sanitised data bucket (in Prod env only)

---

.github/workflows/run-shared-tests.yml

adding back the base image changes

adding back the base image changes

---

apps/pre-award/copilot/environments/addons/sanitised-database-dumps.yml

Adding tags for the sanitise bucket

Sanitise S3 bucket policy

---

apps/pre-award/copilot/environments/addons/sanitised-database-dumps.yml

Adds cross account policy to access sanitised dumps.

FPASF-223: add cross account policy for pre-production environments

---

scripts/aws_connect_db.sh

adding the fab database into a bastion script

adding the fab database into a bastion script

---

.github/workflows/package.yml
.github/workflows/post-deploy.yml
.github/workflows/pre-deploy.yml
.github/workflows/run-shared-tests.yml

https://github.com/astral-sh/setup-uv?tab=readme-ov-file#enable-caching
Ticket: https://mhclgdigital.atlassian.net/browse/FSPT-89

Enable uv cache

---

.pre-commit-config.yaml
scripts/_migrate-pre-award-service-functions.sh
scripts/aws_blank_db.sql
scripts/aws_connect_db.sh
scripts/aws_connect_redis.sh
scripts/list-versions.sh
scripts/migrate-pre-award-service.sh

Adds a pre-commit check that standardises formatting of shell scripts.

Auto-format shell scripts

---

scripts/_migrate-pre-award-service-functions.sh
scripts/migrate-pre-award-service.sh

Minor refactors to the service migration script and functions, and add comments to each function so that hopefully it's easier for other people to understand how this works - and extend it if required.

Service migration scripts refactor

---

.github/workflows/pre-deploy.yml

https://mhclgdigital.atlassian.net/browse/FSPT-153
This is so that pre-award-stores can verify that there are no outstanding DDL changes that need to be committed, eg because python models have changed but a developer has forgotten to run flask db migrate.

Add DB migrations (alembic) check to CI

---

.github/workflows/pre-deploy.yml

I missed a conditional check on this job.

Only run DB migrations if requested

---

.github/workflows/run-shared-tests.yml

Fixes test command not working when run in pipeline

BAU: Fix python test discovery

---

.github/workflows/run-shared-tests.yml

Implements suggestion from: https://github.com/communitiesuk/funding-service-design-workflows/pull/224#discussion_r1896708270

BAU: override step working directory

---

.github/workflows/pre-deploy.yml

https://mhclgdigital.atlassian.net/browse/FSPT-204
With the combined pre-award-frontend and pre-award-stores app, we need to be able to build static assets even for the postgres (API/backend) test suite.

Allow building static assets with postgres tests

---

scripts/aws_connect_db.sh

https://mhclgdigital.atlassian.net/browse/FSPT-179

Add new fsd-pre-award service to DB connector

---

apps/pre-award/copilot/environments/addons/application-deadline-reminder.yml

This PR is a temporary fix so that the correct API hosts are used in production.

Fix API hosts for production

---

.github/workflows/pre-deploy.yml

Removing the `testing-unit-aws` job as this is no longer used

Removing non-postgres test job

---

apps/pre-award/copilot/environments/addons/communities-redirect-cloudfront-function.yml

Fix domain suffixes to reflect new domains

FSPT-228: Update domain suffixes

---

.github/actions/slack_deployment_message/action.yml

I can't be bothered to handle timezone conversion so let's just make it explicit/clear that these timestamps are in UTC

Flag that the timestamps are UTC
