- .github/workflows/deploy.yml
Jira Ticket:
https://digital.dclg.gov.uk/jira/browse/FS-898
I have added environment variables which are basically configs from Locust. 
This will enable us to override these configs in each API store (fund, round and application) to help perform capacity testing. 
I have also added a condition in the run_performance_tests job as the performance tests were skipping in each of the API stores' pipelines.
> FS-898 - Locust configurable running variables & fix to stop performance tests skipping in the pipelines

- .github/workflows/deploy.yml
This would mean as-is the performance tests and accessibility tests would only run on the main branch I believe
> Only deploy main branch to test environment

- .github/workflows/deploy.yml
Pass through git sha in shared workflow, for use by Sentry release automation.
> FS-1677: pass through git sha to app

- .github/workflows/deploy.yml
Follow-up to #16, we need to do this for the test deployment as well as dev.
> FS-1677: pass through git sha to test app

- .github/workflows/deploy.yml
Workflows will use the most up to date python3 version instead of being frozen at 3.10.1.
Requirements.txt will contain the version locked dependancies so this will allow for additional python features and bugfixes to be used.
> BAU-allow-newest-python3

- .github/workflows/deploy.yml
Security doesn't use a requirements file - so there's no need to cache one (and it breaks the pipeline).
> bug security cache.

- .github/workflows/deploy.yml
We should run the tests on the same version we're running on PaaS.
> FS-2022: pin python version to 3.10.x

- .github/workflows/deploy.yml
Preventing tests from running on dependabot PRs as they don't have access to the secrets
> Prevent tests from running on dependabot PRs

- .github/workflows/deploy.yml
Removed params and steps around 'upgrade db' in this shared workflow. They aren't needed as the script to do this is triggered in the app manifest on deploy.
> Removing upgrade db step as doesn't work and not needed

- .github/workflows/tag-to-release.yml
Add tag to release to shared workflows, so it can be shared rather than copied and pasted in each python app.
> FS-2172: add shared workflow for tag to release

- .github/workflows/tag-to-release.yml
This is not required as Github already changes the URL path to include the tag. It will simplify the release process by not having to update number in two places.
Roll-out plan is to push new tags for all apps after this change and then update associated documentation in `terraform-prod` repo.
> FS-2172: remove ref from filename

- .github/workflows/tag-to-release.yml
For apps without a frontend build step the python related steps are unneeded. This should speed up the workflow time with no adverse effects.
> FS-2172: remove unnecessary steps

- .github/workflows/bump-tag.yml
Adds workflow to automate incrementing and pushing tag, idea here is to automate previous manual steps of deploy process i.e. steps 1-4 in https://github.com/communitiesuk/funding-service-design-terraform-prod#updating-python-apps
Rollout plan is to add this to one app to test and then roll out more widely if successful.
> FS-2172: add bump tag workflow

- .github/workflows/deploy.yml
Disable e2e tests on dev as they are unreliable and blocking the pipeline.
> BAU: disable e2e tests on dev

- .github/workflows/run-shared-tests.yml
The yaml updates as per this PR:
https://github.com/communitiesuk/funding-service-design-e2e-checks/pull/130/files
Were not updated in the shared-tests.yml which caused the test report to not upload properly:
https://github.com/communitiesuk/funding-service-design-assessment/actions/runs/4182595026/jobs/7246487099
> BAU: Update shared-tests.yaml to update report path and enable e2e report to run if test pass

- .github/workflows/tag-to-release.yml
Since moving to an Enterprise org it appears GITHUB_TOKEN has defaulted to restricted permissions as described in https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token so we need to specify the correct permissions for our workflows.
> Update github token permissions

- .github/workflows/deploy.yml
adds [concurrency](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency) keys for the deploy steps as PaaS can only do one deployment at a time, to avoid issue where merging too close together causes error e.g.
```
Staging app and tracing logs...
Only one build can be STAGING at a time per application.
FAILED
```
> BAU: add concurrency keys on deploy steps

- .github/workflows/deploy.yml
- .github/workflows/run-shared-tests.yml
Related to https://github.com/communitiesuk/funding-service-design-workflows/pull/43
Added concurrency keys for the e2e and performance tests steps to ensure that the tests don't run across repos at the same time. 
https://docs.github.com/en/actions/using-jobs/using-concurrency
> FS 2385: Add concurrency keys on e2e and performance test steps

- .github/workflows/deploy.yml
- .github/workflows/run-shared-tests.yml
Related to https://github.com/communitiesuk/funding-service-design-e2e-checks/pull/163
I have created a separate workflow step so that e2e tests for application and assessment can now be easily identified in the pipeline run. 
The e2e tests for application and assessment each take env vars which enables these tests to run in isolation. 
This will make it much easier to debug issues between these frontends as each e2e test will now has it's own html report.
Example: https://github.com/communitiesuk/funding-service-design-fund-store/actions/runs/4325665931
> FS-2407: Separate workflow step to separate out e2e tests for Application and Assessment

- .github/workflows/deploy.yml
FS-2415-Standardise_Github_Workflows:
We have added inputs, jobs, and secrets to allow for the current repos not using this shared workflow to now be able to use it. The changes have been tested manually with new and old repos (already using this shared workflow) and all jobs are passing ✅
NB: Secrets are not being set in the shared worflow repo, but instead being called from the respective repos running the worflows.
> fs-2415-standardise-github-workflows

- .github/workflows/deploy.yml
static security job also needs explicit (older) version of bandit for now as bandit has been updated in a few of the other repos using the shared workflow.
> bau-explicit-version-for-bandit

- .github/workflows/tag-to-release.yml
* Add output to the entire workflow that uses an output on the release_tag job
* Add output to the release_tag job that uses an output from a step
Commits 0be754028238d49a8b3fb13a215d4e55f8a52ecb and 47df2d02eda545e9b853e4272e4f63c792185b55 to be removed once testing is complete
> FS-2406: Updating tag-to-release workflow to include tag output

- .github/workflows/run-shared-tests.yml
https://dluhcdigital.atlassian.net/browse/FS-3191
Have separated the e2e tests for assessment to separate jobs in the workflow file per fund. 
This will make it easier to re-run any failed assessment e2e tests for a particular fund without having to run all the e2e assessments again for all the funds if only one of the funds failed. 
I have also changed the node version to match what version we run the e2e tests locally.
> FS-3191: Add separate jobs for Assessment e2e tests for each fund 

- .github/workflows/deploy.yml
- .github/workflows/run-shared-tests.yml
There seems to be some issues with the Test environment which causes the e2e assessment tests to run painfully slow and causes the tests to timeout.
I have now added the needs keyword so that the assessment e2e tests for each fund run in a queue.
This is what the workflow will look like going forward.
> BAU: Add needs keyword to make assessment e2e tests for each fund run in a queue

- .github/workflows/run-shared-tests.yml
Due to changes made in https://github.com/communitiesuk/funding-service-design-e2e-checks/pull/373 to get the e2e assessments to rerun automatically if the test flakes, we don't need to have the e2e assessment test run in a queue on the pipeline as they can now run concurrently again.
> BAU: Remove queue for e2e assessments tests per fund

- .github/workflows/run-shared-tests.yml
Related to:
https://github.com/communitiesuk/funding-service-design-e2e-checks/pull/376
I have amended the yaml file so that it caches the dependencies every time there is a pipeline run through `npm ci.`
> BAU: Cache dependencies for e2e tests

- .github/workflows/run-shared-tests.yml
This PR changes the condition for the NSTF Assessment E2E test so they skip when they're running against Test and UAT.
Reason for this is because Night Shelter is currently closed and there are no further rounds planned in the near future. 
Below is an example of what it will look like when the e2e tests are running. As you can see below, NSTF Assessment E2E test is skipped. 
The example below is from the e2e tests running against Dev.
> BAU: Turn NSTF Assessment E2E Tests Off

- .github/workflows/deploy.yml
- .github/workflows/run-shared-tests.yml
Related to https://github.com/communitiesuk/funding-service-design-e2e-checks/pull/427
The following changes were done:
- Renamed job names for running application and assessment e2e tests
- Removed references to NSTF in the YAML file as the application and assessment window is closed and we no longer need a separate job to run a separate set of assessment e2e tests. All can just run from " e2e-test-assessment"
- Removed references to COF in the YAML file
- Renamed "Rename WebDriver IO Test" to a more meaningful name
- Renamed environment variables
Please note that the e2e test failures are on Dev only due to Fund Store not being configured for certain funds on Dev.
> BAU: Refactor Run Shared Tests YAML File

- .github/workflows/combine-prs.yml
* Moving permissions to be job related not workflow related
* Encapsulating the repository being pushed to
* Utilising Personal Access token (organisation wide) instead of the github token (repository wide) to allow access to the other repositories
+ref: FS-2374
+semver: minor
> Update to combine prs workflow

- .github/workflows/package.yml
Pulling the requirements into the checkout directory means they're being included unnecessarily in the built image e.g.
```
$ docker run -it --entrypoint /bin/sh ghcr.io/communitiesuk/funding-service-design-post-award-submit:smd-334-packeto-buildpack      
$ ls .venv
bin  include  lib  lib64  pyvenv.cfg
```
This changes to use system python for the local requirements build. This also fixes the requirements cache, as it will now find them in the `pip` cache
> remove venv from static assets build

- .github/workflows/package.yml
Uses the `--cache-image` functionality of packeto (https://buildpacks.io/docs/app-developer-guide/using-cache-image/) to store cached layers to speed up subsequent builds. As `--publish` flag is set packeto also publishes the image so there's no need for a separate docker push step. 
Have found in testing this reduces the build and push time by ~50%
e.g. compare: https://github.com/communitiesuk/funding-service-design-post-award-submit/actions/runs/6861712149/job/18665789561 to https://github.com/communitiesuk/funding-service-design-post-award-submit/actions/runs/6879617185/job/18712033034
> build and publish cache image

- .github/workflows/package.yml
Packer cache image was building to communitiesuk/build-paketo-cache-image, which is not a valid location. Adding in the repository to allow for the cache image to be built and stored
> Add Repository info to the packer cache image

- .github/workflows/run-shared-tests.yml
Related to:
https://github.com/communitiesuk/funding-service-design-e2e-checks/pull/462
This PR upgrades the node version to v19 to be compatible with the latest version of chromedriver.
> BAU: Upgrade Node Version to 19 for E2E Tests Workflow

- .github/workflows/run-shared-tests.yml
Related to:
https://github.com/communitiesuk/funding-service-design-e2e-checks/pull/462
This PR upgrades the node version to v19 to be compatible with the latest version of chromedriver.
Also update actions/checkout@v4.1.1 and actions/setup-node@v4 to these respective versions so that it can work with node v19.
> BAU: Upgrade Node Version and packages associated with E2E test workflow

- apps/pre-award/copilot/environments/addons/assessment-import-queue.yml
It is necessary to have DeleteMessage to remove a message once it is handled.
> BAU - Allow delete message for the assessment queue

- apps/pre-award/copilot/environments/prod/manifest.yml
* Adding eu-west-2 certificate for the ELBs, different from the us-east-1 certificate for the cloudfront distribution
+ref: BAU
+semver: minor
> Adding certificates

- apps/pre-award/copilot/environments/addons/form-uploads.yml
https://dluhcdigital.atlassian.net/browse/FS-3907
After applying to dev, logging is enabled here: https://s3.console.aws.amazon.com/s3/buckets/fsd-form-uploads-dev?region=eu-west-2&tab=properties and the new bucket is created with an access policy ready for writing.
> FS-3907 - add access logging to fsd-form-uploads

- .github/workflows/post-deploy.yml
- .github/workflows/run-shared-tests.yml
Added arguments to workflow to specify whether to run the assessment or application e2e tests separately.
> updated workflow to take arguments about which e2e tests to execute

- .github/workflows/combine-prs.yml
- .github/workflows/run-shared-tests.yml
https://dluhcdigital.atlassian.net/browse/FS-3974
Use a later version of the app-token retrieval so expired tokens are revoked gracefully without failing the jobs.
> FS-3974 - Use later version of token generator to fail gracefully

- scripts/aws_connect_db.sh
https://dluhcdigital.atlassian.net/browse/FS-4041
On Windows `ps -t...` doesn't work, so when it doesn't, try python instead to kill the session manager, which means it'll be possible to run a connection again without closing the terminal completely first.
> FS-4041 - Alternate version for Windows

- .github/workflows/just-run-tests.yml
- .github/workflows/post-deploy.yml
- .github/workflows/run-shared-tests.yml
Continuing Rob's fix from FS-4224 and applying it to assessment as well
- Updating the name of the report file that gets uploaded to include the environment name and a timestamp to prevent name conflicts when a job is rerun or across multiple environments
> Bau fix assessment reports

- .github/workflows/post-deploy.yml
Bumped the ZAP version to 0.10.0 as the previous version no longer existed and was breaking builds
> bumped zap scan version to 0.10.0

- .github/workflows/standard-deploy.yml
As dependabot doesn't have access to secrets it cannot deploy successfully.
You can see this has caused many failures on dependabot PRs e.g. https://github.com/communitiesuk/funding-service-design-account-store/pull/215
> BAU: Don't run deploy if user is dependabot

- .github/workflows/determine-jobs.yml
Removing `dev` from the automatic list of jobs generated when a workflow runs. It will now:
- Deploy to the selected environment if run manually
- Deploy to nothing if from a branch
- Deploy to `test`, `uat` and `prod` from main.
> Removing dev from list of jobs generated

- .github/workflows/determine-jobs.yml
Fixing the case where there are no jobs - returning an empty array instead of nothing
> fixing empty jobs

- .github/workflows/pre-deploy.yml
Updated the test tasks in the actions so that:
- DB requirements are not installed for frontend tests
- Frontend requirements are not installed for db tests
> removing db requirements from frontend tests

- scripts/aws_db_dump_restore.sh
In the current post-award(data-store) world, our dbname is `data_api_db`. In pre-award(post-award) world, our dbname is `post_award`.
Using the `--create` flag means that we are restoring into target db under the `data_api_db` name, which is wrong.
If we drop `--create` and just use `--clean`, then everything gets restored into the database we're connected to - which will be from the URI, and be the correct (`post_award`) location.
> Don't use `--create`

- .github/workflows/run-shared-tests.yml
E2E tests are failing to run because the version needs to be updated as the e2e tests repo upgraded to Node 21
> FS-3840: Post deploy E2E tests workflow to use Node 21

- apps/pre-award/copilot/environments/addons/post-award-find-download-files.yml
We missed this lifecycle configuration when migrating to the monolith, seemingly.
> Find download reports should expire after 7 days

- .github/workflows/update-preaward-env.yml
This was causing a duplicate deployment on merge e.g.
And one of these would fail.
There is no need for the additional check as we have branch protection on pushes to `main`.
> BAU: Remove duplicate trigger

- apps/pre-award/copilot/environments/addons/sanitised-database-dumps.yml
Explicitly set a deterministic name, In order to make it easier to look up the x-account bucket
> FPASF-223: set deterministic name for sanitised dumps bucket

- .github/workflows/post-deploy.yml
I tried a few different things example verbose run: 
https://github.com/communitiesuk/funding-service-design-authenticator/actions/runs/11631722517/job/32393348190?pr=349
It's running on everything inside the project...
`-lll` makes it to throw an error only for `High`  level severity issues.
It's a bit annoying. But perhaps easiest is to clone [this branch](https://github.com/communitiesuk/funding-service-design-authenticator/pull/349/files).
If you want to test on local.
1. cd to authenticator dir
2. source venv
3. `pip install -r requirements-dev.txt bandit==1.7.4`
4. `bandit -v -r . -x /.venv -lll` (you have to ignore `.venv` on local)
> Bandit fix

- scripts/aws_connect_db.sh
Could not get `yq` to work on linux. We had this problem a while ago when we were doing the monolith migration.
`jq` should work without any troubles.
If you have a Mac, please try see if you can connect to `test` db.
> Switch from yq to jq

- .github/workflows/package.yml
- .github/workflows/pre-deploy.yml
Caching will be re-enabled once we're switched over to `uv` fully.
Some `uv`-converted apps are now failing CICD because dependencies aren't getting installed by `pip`, so there's no cache for `pip` to save on teardown, and it throws an error for that situation.
Also fixes a bug where `uv` would only export `requirements.txt` if `assets_required` was set as true.
[Example of bad](https://github.com/communitiesuk/funding-service-design-assessment-store/actions/runs/11798848385/job/32865984294)
[Example of fix]()
> Remove pip cache - failing some runs with uv

- .github/workflows/package.yml
- .github/workflows/post-deploy.yml
- .github/workflows/pre-deploy.yml
- .github/workflows/run-shared-tests.yml
https://mhclgdigital.atlassian.net/browse/FSPT-87
All of our apps are now using [`uv`](https://docs.astral.sh/uv/) for their dependency management and deployment, so we don't need the old pip-style codepath anymore.
> Remove old pip-style path from workflows

- .github/workflows/post-deploy.yml
- .github/workflows/pre-deploy.yml
- .github/workflows/standard-deploy.yml
- scripts/aws_connect_db.sh
Updates AWS deployment workflows:
- Removes hardcoded `fsd-`/`funding-service-design` prefix
- Passes and injects full built image location
- Removes ambiguity around database URL for unit tests
- Adds line to `init` a service if it's the first time it's getting deployed
- Update `aws_connect_db.sh` script to add `pre-award-stores` as an option
> FSPT-63: Update workflows for new combined pre-award-stores repo

- scripts/_migrate-pre-award-service-functions.sh
- scripts/migrate-pre-award-db.sh
https://mhclgdigital.atlassian.net/browse/FSPT-68
We are planning to shift data that's currently in our separate pre-award stores to a single new database so that we can have everything in one place and simplify our architecture.
This script aims to provide a simple, automated and validated way of transferring that data.
It expects the tables to already exist in the database, but they must be empty (and the script checks that they are).
* Checkout the `feature/FSPT-56-add-combined-stores-repos` branch on docker runner
* Do a `make up`
* In a new terminal, run `./scripts/migrate-pre-award-db.sh -s postgresql://postgres:password@localhost:5432/fund_store -t postgresql://postgres:password@localhost:5432/pre_award_stores`.
* You should see a successful result.
* Do it again and you should see …
> Add pre-award-stores DB migration scripts

- apps/pre-award/copilot/environments/addons/application-deadline-reminder.yml
We are migrating from a bunch of "microservice"-y pre-award API services to a single combined "pre-award-stores" API.
After we've migrated, we need to point all apps/lambdas/services/etc to the new service, and the fund-store API endpoints have now been namespaced under a /fund prefix.
All of the other apps will read the fund-store host from an AWS parameter store thing, but lambdas aren't able to read this in the same way - they would be expected to retrieve the value at runtime.
I don't want to change the code to support this, and since this is the only outlier I'm going to take the simplest approach - just update the fund store host in a PR. We can manage this manually as we do the migration/switchover on the day.
> Update fund-store URL for combined pre-award-stores

- apps/pre-award/copilot/environments/addons/post-award-cluster.yml
We omitted this when setting up this DB but it is best practice to retain a week of DB snapshots. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html#cfn-rds-dbinstance-backupretentionperiod for context.
> BAU: update database retention period

- apps/pre-award/copilot/environments/addons/assessment-import-queue.yml
- apps/pre-award/copilot/environments/addons/notification-queue.yml
These are mistakenly globally accessible (read/write), but they should definitely not be.
> Limit queue access to same account

- .github/workflows/run-shared-tests.yml
The end to end tests now read secrets from AWS as needed. In order for them to do this, we need to configure AWS credentials as part of the workflow.
```
[chrome 131.0.6778.85 linux #0-2] 1) E2E test to create an application for High Street Rental Auction Fund should successfully create and submit a new application for HSRA
[chrome 131.0.6778.85 linux #0-2] Error: Region is missing
[chrome 131.0.6778.85 linux #0-2]     at async FundingServiceSecrets.getBasicAuth (/home/runner/work/funding-service-design-notification/funding-service-design-notification/funding-service-design-e2e-checks/test/secrets.js:26:34)
```
> OIDC auth to AWS for end to end tests

- .github/workflows/run-shared-tests.yml
This lets github pull the correct AWS_ACCOUNT id based on the environment.
```
Run aws-actions/configure-aws-credentials@v4
with:
role-to-assume: arn:aws:iam:::role/GithubCopilotDeploy
role-session-name: __copilot_
aws-region: eu-west-[2](https://github.com/communitiesuk/funding-service-design-notification/actions/runs/12138503705/job/33857421740#step:3:2)
audience: sts.amazonaws.com
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Assuming role with OIDC
Error: Could not assume role with OIDC: Request ARN is invalid
```
> Tell github about the environment

- .github/workflows/just-run-tests.yml
This matches the other changes made for e2e tests to run more efficiently.
> BAU: Adds AWS_ACCOUNT secret to `just_run_tests` workflow

- .github/workflows/run-shared-tests.yml
This ensures the correct environment is referenced, rather than defaulting to `test`: https://github.com/communitiesuk/funding-service-design-e2e-checks/blob/main/test/environment.js
> Set E2E_ENVIRONMENT variable

- .github/workflows/standard-deploy.yml
pre-award-stores and account-store currently both build a new image using a Dockerfile, which is then deployed into ECS to run database migrations. This image differs from the one used to run the web services themselves, and is generally built in a less secure way.
For both security and speed, it's easier to re-use the image that paketo has build to run database migrations.
By deprecating these old fields, we can start switching all callers over to pass `image_location` instead, which will point at the existing paketo image.
> Deprecate old workflow inputs, prefer image_location

- .github/workflows/standard-deploy.yml
Remove the unused inputs for this workflow, and pass the `image_location` into the migration scripts (which will be updated in separate per-repo PRs) so that they can reuse this image rather than building a new image from the Dockerfile in the repo. This will result in a more consistent image used for DB changes, and should result in faster deployments because we don't build the image twice (once in paketo, once with a Dockerfile).
> Run DB migrations using paketo image

- readmes/python-repos-ide-setup.md
- readmes/python-repos-paketo.md
The [funding service design base](https://github.com/communitiesuk/funding-service-design-base) repository won't be as relevant now that are reducing the number of repositories and steering away from a microservice architecture.
It doesn't look like it was ever used in anger so remove references to it before archiving.
Of note while removing this it looks like some of these instructions will need to change as we move to a single repository - some may already be out of date so an audit might be useful as a step at the end of this work.
> FSPT-157 Remove references to funding service design base repo

- scripts/_migrate-pre-award-service-functions.sh
- scripts/migrate-pre-award-service.sh
For the post-award scheduled job and pre-award application deadline reminder lambda we'll run the workflows and environment updates manually -- they'll be one off for this context and shouldn't be needed by anything else that will run this script.
> FSPT-190 Add account store to migrate script

- scripts/_migrate-pre-award-service-functions.sh
We no longer have separate (apply) frontend and assessment frontend apps
- these have been combined into fsd-pre-award-frontend.
So we only need to roll that one service now
> Update service migrartion script for fsd-pre-award-frontend

- scripts/_migrate-pre-award-service-functions.sh
pre-award-stores also reads the ACCOUNT_STORE_API_HOST value from parameter store, so we need to roll that service after changing it before disabling maintenance mode.
> Also roll pre-award-stores to pick up new account store host

- apps/pre-award/copilot/environments/addons/application-deadline-reminder.yml
Just point to the new store, this will likely become scheduled job on
the main app to reduce moving parts, fine for it to be fixed for now
Previous commit (fetching from SSM doesn't appear to be supported by the lambda resource in the addons):
~~This should allow the environment variable to be retrieved from the param store at the time that this is run.~~
~~Note that similar to an ECS task definition this will only set the environment for the lambda at the time that this is run, the lambda will then use that value unless its deployed again (which presumably happens a lot less than the apps).~~
~~If we wanted to guarantee the lambda was using the latest references to stores in the param store (unlikely as we're reducing our data stores down to one database) we could use a lambda extension …
> FSPT-190 Get the account store URI from the parameter store

- .github/workflows/just-run-tests.yml
- .github/workflows/run-shared-tests.yml
Adds option to run the python tests to 'just run tests'
I have tested running this workflow e.g. https://github.com/communitiesuk/funding-service-design-workflows/actions/runs/12430575954
> Add manual workflow to trigger Python E2E tests

- .github/workflows/just-run-tests.yml
- .github/workflows/post-deploy.yml
These tests do not work in the UAT environment.
> Make python e2e tests only run in dev+test

- .github/workflows/post-deploy.yml
At the moment, e2e tests running in dev will block e2e tests running in test/uat because they are all in the same concurrency group.
This adds the environment name to the concurrency group so that tests can run in different environments at the same time.
> Make the e2e tests/etc run simultaneously per environment

- .github/workflows/notify-slack-deployment-failed.yml
- .github/workflows/post-deploy.yml
- .github/workflows/run-shared-tests.yml
- .github/workflows/standard-deploy.yml
When a deployment pipeline fails, we've seen developers not quickly notice and own getting it resolved.
This patch integrates a Slack Workflow that the github action can call which will send a chat message to one of our dev channels.
I wanted to have the app `@tag` the user in slack who committed the code/ran the workflow, but doing the lookup from github actor -> slack user is not a super reliable lookup, so I haven't bothered. It might be a nice addition in the future though.
See todo list in comment on ticket: https://mhclgdigital.atlassian.net/browse/FSPT-220. PRs need to be merged around the same time, and there are some pre-reqs that need to be done by a github/slack admin.
> Enable slack notifications for failed deploy

- .github/workflows/standard-deploy.yml
We don't notify to slack on failed dev deploys, so the secrets are optional.
> Don't require slack secrets on standard-deploy

- .github/workflows/standard-deploy.yml
This is to avoid a case where jobs are deployed with a matrix or similar names and the copilot command can't determine which service to deploy without it being specified.
> BAU: Add app_name variable to copilot deploy command

- .github/workflows/notify-slack-deployment-failed.yml
It's OK for this to be unset - it's only required on push events.
> Don't require compare_url

- .github/workflows/package.yml
This is so that we have an easier reference to use for eg pulling locally to inspect images.
From `pack build --help`:
-t, --tag strings                  Additional tags to push the output
image to. Tags should be in the format 'image:tag' or
'repository/image:tag'. Repeat for each tag in order, or supply once by
comma-separated list
> Always tag latest for built images

- .github/workflows/update-preaward-env.yml
- apps/pre-award/copilot/environments/addons/application-deadline-reminder.yml
AWS lambda doesn't provide the requests library out of the box. As a result, we package the requests library as part of the (Github actions) deployment of the lambda to ensure it includes all necessary dependencies (the alternative is to create a lambda layer - this is a very similar process but would require a manual step in uploading the requests library to S3).
> Install requests on github actions deploy

- .github/actions/slack_deployment_message/action.yml
- .github/workflows/standard-deploy.yml
Add steps to the standard deployment pipeline that post messages to a deployments slack channel to make it clear when deployments start and finish.
For now, we just do this for the production environment. This should help identify if errors are/may be related to a recent deployment.
The various messages it shows (you get 1 message per deployment, which is updated - these are just all of the various things you might see, but you wouldn't get all three visible at once). Except ignore the 'view code changes' link - I've removed that for all states because of faffy edge cases.
Need to add SLACK_DEPLOYMENTS_CHANNEL_ID org-level secret, add it to all the relevant repos, and raise PRs on all of those repos to pass the secret into the standard-deploy action.
> Post messages when deployments (to prod) start and end

- .github/workflows/post-deploy.yml
So that we can upload an artifact for test and uat without it complaining about overlapping names.
> add env artifact name

- apps/pre-award/copilot/environments/addons/application-deadline-reminder.yml
This security group grants direct access to the Fund Store database so we don't believe it is required by the Lambda. We have also run the Lambda on dev without this permission in the console without any change in behaviour observed.
> FSPT-250: Remove Fund Store cluster Security group from lambda

- apps/pre-award/copilot/environments/addons/form-uploads.yml
Update allowed origins list ahead of domain migration.
(Also removes some erroneous CORS configuration on the logs bucket)
> FSPT-228: update allowed origins

- apps/pre-award/copilot/environments/addons/communities-redirect-cloudfront-function.yml
- apps/pre-award/copilot/environments/overrides/README.md
- apps/pre-award/copilot/environments/overrides/cfn.patches.yml
Adds a cloudfront function to support domain name move
* Redirect to renamed communities.gov.uk services
* Redirect to un-renamed communities.gov.uk services
* passthrough any other requests
N.B. Weird interpolation syntax is due to mixing AWS and Javascript interpolation, syntax is as described in: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html#w32aac23c24c67b7
Deploying this branch should create a Cloudfront Function
This can then be tested using the Test function in the Cloudfront Functions console by setting the host header for the scenario under test.
I have also tested by deploying on dev with the function association temporarily.
> FSPT-243: add redirect cloudfront function

- .github/workflows/update-preaward-env.yml
- apps/pre-award/copilot/environments/dev/manifest.yml
- apps/pre-award/copilot/environments/prod/manifest.yml
- apps/pre-award/copilot/environments/test/manifest.yml
- apps/pre-award/copilot/environments/uat/manifest.yml
Adds certificates to support domain migration 
(also refactors to use [variable substitution](https://aws.github.io/copilot-cli/docs/developing/manifest-env-var/) for account id)
I have verified these certicates have been validated successfully in the console, so should attach to the resources successfully in each environment
> FSPT-228: Add test, uat certificates & update prod certificates

- apps/pre-award/copilot/environments/overrides/cfn.patches.yml
Enables the Cloudfront Redirect function added in https://github.com/communitiesuk/funding-service-design-workflows/pull/266
N.B. will disable the workflow after deployment to Test to stop it going to UAT and Production prematurely.
> FSPT-228: enable redirect cloudfront function

- apps/pre-award/copilot/environments/addons/communities-redirect-cloudfront-function.yml
Fix the redirect function. 
Redirect location should be an absolute path. Previously this was missing from this condition causing a relative path to be returned.
Have tested this using the Cloudfront Functions test console.
> FSPT-228: add protocol to redirect location in unchanged hostname case

- .github/workflows/list-versions.yml
- .github/workflows/run-shared-tests.yml
- .github/workflows/standard-deploy.yml
Fixes a small syntax error and typo in the `standard_deploy` workflow (neither of which were breaking errors but good to have the variables properly injected where needed).
> BAU: Fix typos and syntax errors in deploy workflow

- .github/workflows/determine-jobs.yml
- .github/workflows/just-run-tests.yml
- .github/workflows/list-versions.yml
- .github/workflows/notify-slack-deployment-failed.yml
- .github/workflows/package.yml
- .github/workflows/post-deploy.yml
- .github/workflows/pre-deploy.yml
- .github/workflows/run-shared-tests.yml
- .github/workflows/standard-deploy.yml
- .github/workflows/update-preaward-env.yml
For some GitHub workflow jobs we have nice, readable names like "Check DB migrations" while for others we don't have a name defined and so are forced to use whatever hyphenated label we've assigned to the job in the code e.g., `testing-unit-postgres-aws`.
This PR adds names to all jobs.
Example before:
Example after:
> Adding simple names to all jobs for readability

- apps/pre-award/copilot/environments/addons/communities-redirect-cloudfront-function.yml
Updates redirects to 301
(Now migration has been completed successfully we should return a 301 to update browsers, search engines etc permanently)
also moves query string logic after initial return statement to stop that code block being executed unnecessarily
> FSPT-228: Update redirect status code

- .github/workflows/run-shared-tests.yml
Artifacts weren't found previously because they were in a sub-folder. This adds a wildcard so they should be found
e.g. https://github.com/communitiesuk/funding-service-pre-award/actions/runs/14039813318/job/39452192284#step:8:17
`Warning: No files were found with the provided path: test-results/. No artifacts will be uploaded.`
> BAU: Include wildcard for artifacts

- apps/pre-award/copilot/environments/overrides/cfn.patches.yml
Enables Shield Advanced protection on the Cloudfront Distribution.
I have tested this on Dev and confirmed it is enabled in the Shield Console
> FLS-1271: enable shield protection on the cloudfront distribution

- apps/pre-award/copilot/environments/addons/form-uploads.yml
[Ticket](https://mhclgdigital.atlassian.net/browse/FLS-1309)
We need to enable s3 versioning before replacing uploaded files, for the CHAM issue aftermath.
> FLS-1309: Enable s3 Versioning 
